### ISSUE TITLE
New uploads do not accept default folder.

### ISSUE THREAD

**Issue by wolfhoundjesse** [ArmyMusicOnline/ami#295] opened 2018-01-04 21:21 UTC

**Comment by kjbetz** [comment] 2018-05-23 16:50
Duplicate of #324 ? Fixed by commit https://github.com/ArmyMusicOnline/ami/commit/b21dffaca00fdb0fdfaacf95d55007d5d880c20e

**Closed by kjbetz** 2018-05-23 16:50 UTC
Labels: Media, bug
